# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_v_x: 0.5
speed_lim_v_y: 0.35

speed_lim_w: 0.4

accel_lim_v: 1.0
accel_lim_w: 2.0

# Optional parameters
frequency: 10.0
decel_factor: 1.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 2