DWAPlannerROS:
  #http://wiki.ros.org/dwa_local_planner

  min_vel_trans: 0.01
  max_vel_trans: 0.5

  min_vel_x: -0.025
  max_vel_x: 0.5

  min_vel_y: 0.0
  max_vel_y: 0.0

  max_vel_rot: 1.0
  min_vel_rot: -1.0

  acc_lim_trans: 1.7
  acc_lim_x: 1.7
  acc_lim_y: 0.0
  acc_lim_theta: 3

  trans_stopped_vel: 0.1
  theta_stopped_vel: 0.1

  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.34

  sim_time: 3.5
  sim_granularity: 0.1
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  path_distance_bias: 34.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05

  forward_point_distance: 0.2
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  use_dwa: true

  prune_plan: false
