global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0 #before: 5.0
  publish_frequency: 0.5 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 10.0
  inflation_radius: 0.55